server:
  port: 8080

web-client:
  github-api-base: https://api.github.com
  github-api-user-info: /users/

springdoc:
  swagger-ui:
    path: /

aggregator:
  time-window-for-saving-occurrences-ms: 7200000